### ISSUE TITLE
Nice to have: screenshot

### ISSUE THREAD

**Issue by nmr8acme** [googlesamples/androidtv-VisualGameController#1]
Would be great to have a screenshot in `README.md` so we can get a quick idea of what this demo is about. Description seems adequate, but a screenshot seems better.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
